# -*- coding: utf-8 -*-

"""
   APIMATICCalculatorLib.Configuration

   This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
"""

class Configuration :
    # The base Uri for API calls
    BASE_URI = "https://examples.apimatic.io/apps/calculator"


